package ext.tree;

import javax.faces.context.FacesContext;

import ext.annotation.InstanceOf;
import ext.annotation.ParseConfigMode;
import ext.annotation.PersistenceMode;
import ext.annotation.ReferenceMode;
import ext.base.ExtOutput;

/**
 *Note:This java code is auto generated by abner,do not edit it. This class
 * provides the default UI implementation for Ext TreeNodes. The TreeNode UI
 * implementation is separate from the tree implementation, and allows
 * customizing of the appearance of tree nodes.<br>
 * <p>
 * If you are customizing the Tree's user interface, you may need to extend this
 * class, but you should never need to instantiate this class.<br>
 * </p>
 * 
 * <p>
 * This class provides access to the user interface components of an Ext
 * TreeNode, through <a
 * href="output/Ext.tree.TreeNode.html#Ext.tree.TreeNode-getUI"
 * ext:member="getUI" ext:cls="Ext.tree.TreeNode">Ext.tree.TreeNode.getUI</a>
 * </p>
 */
@InstanceOf("Ext.tree.TreeNodeUI")
@ParseConfigMode(name = "uiProvider", pmode = PersistenceMode.ParentProperty, rmode = ReferenceMode.Var)
public class TreeNodeUI extends ExtOutput {
	public static final String COMPONENT_TYPE = "Ext.tree.TreeNodeUI";
	public static final String COMPONENT_FAMILY = "Ext.tree.TreeNodeUI";

	/**
	 * <p>
	 * Create a new {@link TreeNodeUI} instance with default property values.
	 * </p>
	 */
	public TreeNodeUI() {
		super();
		setRendererType(COMPONENT_FAMILY);
	}

	public String getFamily() {
		return (COMPONENT_FAMILY);
	}

	private Object[] _values;

	public Object saveState(FacesContext _context) {
		if (_values == null) {
			_values = new Object[1];
		}
		_values[0] = super.saveState(_context);

		return _values;
	}

	public void restoreState(FacesContext _context, Object _state) {
		_values = (Object[]) _state;
		super.restoreState(_context, _values[0]);

	}
}