package ext;

import javax.faces.context.FacesContext;

import ext.annotation.InstanceOf;

/**
 *Note:This java code is auto generated by abner,do not edit it.
 * 
 * <p>
 * Used to provide a sizable space in a layout.
 * </p>
 */
@InstanceOf("Ext.Spacer")
public class Spacer extends BoxComponent {
	public static final String COMPONENT_TYPE = "Ext.Spacer";
	public static final String COMPONENT_FAMILY = "Ext.Spacer";

	/**
	 * <p>
	 * Create a new {@link Spacer} instance with default property values.
	 * </p>
	 */
	public Spacer() {
		super();
		setRendererType(COMPONENT_FAMILY);
	}

	public String getFamily() {
		return (COMPONENT_FAMILY);
	}

	private Object[] _values;

	public Object saveState(FacesContext _context) {
		if (_values == null) {
			_values = new Object[1];
		}
		_values[0] = super.saveState(_context);

		return _values;
	}

	public void restoreState(FacesContext _context, Object _state) {
		_values = (Object[]) _state;
		super.restoreState(_context, _values[0]);

	}
}