package ext;

import javax.faces.context.FacesContext;

import ext.annotation.InstanceOf;
import ext.base.ExtOutput;

/**
 *Note:This java code is auto generated by abner,do not edit it. An object that
 * represents a group of <a href="output/Ext.Window.html"
 * ext:cls="Ext.Window">Ext.Window</a> instances and provides z-order management
 * and window activation behavior.
 */
@InstanceOf("Ext.WindowGroup")
public class WindowGroup extends ExtOutput {
	public static final String COMPONENT_TYPE = "Ext.WindowGroup";
	public static final String COMPONENT_FAMILY = "Ext.WindowGroup";

	/**
	 * <p>
	 * Create a new {@link WindowGroup} instance with default property values.
	 * </p>
	 */
	public WindowGroup() {
		super();
		setRendererType(COMPONENT_FAMILY);
	}

	public String getFamily() {
		return (COMPONENT_FAMILY);
	}

	private Object[] _values;

	public Object saveState(FacesContext _context) {
		if (_values == null) {
			_values = new Object[1];
		}
		_values[0] = super.saveState(_context);

		return _values;
	}

	public void restoreState(FacesContext _context, Object _state) {
		_values = (Object[]) _state;
		super.restoreState(_context, _values[0]);

	}
}