package ext.data;

import javax.faces.context.FacesContext;

import ext.annotation.InstanceOf;
import ext.annotation.ParseConfigMode;
import ext.annotation.PersistenceMode;
import ext.annotation.ReferenceMode;

/**
 *Note:This java code is auto generated by abner,do not edit it. DataWriter
 * extension for writing an array or single <a
 * href="output/Ext.data.Record.html"
 * ext:cls="Ext.data.Record">Ext.data.Record</a> object(s) in preparation for
 * executing a remote CRUD action via XML.
 */
@InstanceOf("Ext.data.XmlWriter")
@ParseConfigMode(ui = false, name = "writer", pmode = PersistenceMode.ParentProperty, rmode = ReferenceMode.Var)
public class XmlWriter extends DataWriter {
	public static final String COMPONENT_TYPE = "Ext.data.XmlWriter";
	public static final String COMPONENT_FAMILY = "Ext.data.XmlWriter";

	/**
	 * <p>
	 * Create a new {@link XmlWriter} instance with default property values.
	 * </p>
	 */
	public XmlWriter() {
		super();
		setRendererType(COMPONENT_FAMILY);
	}

	public String getFamily() {
		return (COMPONENT_FAMILY);
	}

	private Object[] _values;

	public Object saveState(FacesContext _context) {
		if (_values == null) {
			_values = new Object[1];
		}
		_values[0] = super.saveState(_context);

		return _values;
	}

	public void restoreState(FacesContext _context, Object _state) {
		_values = (Object[]) _state;
		super.restoreState(_context, _values[0]);

	}
}