package ext.layout;

import javax.faces.context.FacesContext;

import ext.annotation.InstanceOf;
import ext.annotation.Layout;
import ext.annotation.LayoutType;
import ext.annotation.ParseConfigMode;
import ext.annotation.PersistenceMode;
import ext.annotation.ReferenceMode;

/**
 *Note:This java code is auto generated by abner,do not edit it. Layout manager
 * implicitly used by Ext.Toolbar.
 */
@Layout(LayoutType.toolbar)
@InstanceOf("Ext.layout.ToolbarLayout")
@ParseConfigMode(ui = false, pmode = PersistenceMode.InnerProperty, rmode = ReferenceMode.Config)
public class ToolbarLayout extends ContainerLayout {
	public static final String COMPONENT_TYPE = "Ext.layout.ToolbarLayout";
	public static final String COMPONENT_FAMILY = "Ext.layout.ToolbarLayout";

	/**
	 * <p>
	 * Create a new {@link ToolbarLayout} instance with default property values.
	 * </p>
	 */
	public ToolbarLayout() {
		super();
		setRendererType(COMPONENT_FAMILY);
	}

	public String getFamily() {
		return (COMPONENT_FAMILY);
	}

	private Object[] _values;

	public Object saveState(FacesContext _context) {
		if (_values == null) {
			_values = new Object[1];
		}
		_values[0] = super.saveState(_context);

		return _values;
	}

	public void restoreState(FacesContext _context, Object _state) {
		_values = (Object[]) _state;
		super.restoreState(_context, _values[0]);

	}
}