package ext.ux.data;

import javax.faces.context.FacesContext;

import ext.annotation.InstanceOf;
import ext.annotation.ParseConfigMode;
import ext.annotation.PersistenceMode;
import ext.annotation.ReferenceMode;
import ext.data.MemoryProxy;

/**
 *Note:This java code is auto generated by abner,do not edit it.
 * 
 * <p>
 * Paging Memory Proxy, allows to use paging grid with in memory dataset
 * </p>
 */
@InstanceOf("Ext.ux.data.PagingMemoryProxy")
@ParseConfigMode(ui = false, name = "proxy", pmode = PersistenceMode.ParentProperty, rmode = ReferenceMode.Var)
public class PagingMemoryProxy extends MemoryProxy {
	public static final String COMPONENT_TYPE = "Ext.ux.data.PagingMemoryProxy";

	/**
	 * <p>
	 * Create a new {@link PagingMemoryProxy} instance with default property
	 * values.
	 * </p>
	 */
	public PagingMemoryProxy() {
		super();
		setRendererType(COMPONENT_TYPE);
	}

	public String getFamily() {
		return (COMPONENT_TYPE);
	}

	private Object[] _values;

	public Object saveState(FacesContext _context) {
		if (_values == null) {
			_values = new Object[1];
		}
		_values[0] = super.saveState(_context);

		return _values;
	}

	public void restoreState(FacesContext _context, Object _state) {
		_values = (Object[]) _state;
		super.restoreState(_context, _values[0]);

	}
}