package ext.ux.form;

import javax.faces.context.FacesContext;

import ext.annotation.InstanceOf;
import ext.annotation.UXResources;
import ext.form.TwinTriggerField;

/**
 *Note:This java code is auto generated by abner,do not edit it. Creates a
 * field utilizing Ext.ux.Spinner
 */
@UXResources(js = {"ext[version]/ux/SearchField.js"})
@InstanceOf("Ext.ux.form.SearchField")
public class SearchField extends TwinTriggerField {
	public static final String COMPONENT_TYPE = "Ext.ux.form.SearchField";
	public static final String COMPONENT_FAMILY = "Ext.ux.form.SearchField";

	/**
	 * <p>
	 * Create a new {@link SearchField} instance with default property values.
	 * </p>
	 */
	public SearchField() {
		super();
		setRendererType(COMPONENT_TYPE);
	}

	public String getFamily() {
		return (COMPONENT_TYPE);
	}

	private Object[] _values;

	public Object saveState(FacesContext _context) {
		if (_values == null) {
			_values = new Object[1];
		}
		_values[0] = super.saveState(_context);

		return _values;
	}

	public void restoreState(FacesContext _context, Object _state) {
		_values = (Object[]) _state;
		super.restoreState(_context, _values[0]);

	}
}