package ext.ux.form;

import javax.faces.context.FacesContext;

import ext.annotation.InstanceOf;
import ext.annotation.UXResources;
import ext.annotation.XType;
import ext.form.NumberField;

/**
 *Note:This java code is auto generated by abner,do not edit it. Creates a
 * field utilizing Ext.ux.Spinner
 */
@XType("spinnerfield")
@UXResources(js = {"ext[version]/ux/Spinner.js","ext[version]/ux/SpinnerField.js"},css="ext[version]/ux/css/Spinner.css")
@InstanceOf("Ext.ux.form.SpinnerField")
public class SpinnerField extends NumberField {
	public static final String COMPONENT_TYPE = "Ext.ux.form.SpinnerField";
	public static final String COMPONENT_FAMILY = "Ext.ux.form.SpinnerField";

	/**
	 * <p>
	 * Create a new {@link SpinnerField} instance with default property values.
	 * </p>
	 */
	public SpinnerField() {
		super();
		setRendererType(COMPONENT_TYPE);
	}

	public String getFamily() {
		return (COMPONENT_TYPE);
	}

	private Object[] _values;

	public Object saveState(FacesContext _context) {
		if (_values == null) {
			_values = new Object[1];
		}
		_values[0] = super.saveState(_context);

		return _values;
	}

	public void restoreState(FacesContext _context, Object _state) {
		_values = (Object[]) _state;
		super.restoreState(_context, _values[0]);

	}
}